sudo: required
services: 
  - docker

before_install:
  - docker build -t tinee/react-test -f ./client/dev.dockerfile ./client

script:
  - docker run tinee/react-test npm run test -- --coverage

after_success: 
  - docker build -t tinee/multi-client -f ./client/prod.dockerfile ./client
  - docker build -t tinee/multi-nginx -f ./nginx/prod.dockerfile ./nginx
  - docker build -t tinee/multi-server -f ./server/prod.dockerfile ./server
  - docker build -t tinee/multi-worker -f ./worker/prod.dockerfile ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u=tinee --password-stdin
  - docker push tinee/multi-client
  - docker push tinee/multi-nginx
  - docker push tinee/multi-server
  - docker push tinee/multi-worker
